export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
